name: Build Android APK
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04 # Hata vermeyen sabit sürüm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev xz-utils liblzma-dev libffi-dev uuid-dev openjdk-17-jdk python3-pip
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: Build APK
        run: |
          # Buildozer'ı çalıştırılabilir yola ekle ve derlemeyi başlat
          export PATH=$PATH:$HOME/.local/bin
          yes y | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Uygulama-APK
          path: bin/*.apk
